#!/bin/sh

# Setup initial config if doesn't exist yet
test -e $SNAP_DATA/daemon_arguments || cp $SNAP/etc/ceph_exporter/daemon_arguments.example $SNAP_DATA/daemon_arguments

. $SNAP_DATA/daemon_arguments
echo "* Running $SNAP/bin/ceph_exporter with args: $ARGS"
export LD_LIBRARY_PATH=$SNAP/lib/x86_64-linux-gnu:$SNAP/usr/lib/x86_64-linux-gnu:$SNAP/usr/lib/x86_64-linux-gnu/ceph
$SNAP/bin/ceph_exporter -ceph.config /var/snap/prometheus-ceph-exporter/current/ceph.conf -ceph.user exporter $ARGS
