name: prometheus-ceph-exporter
version: nautilus-edge
base: core18 #GLIBC_2.25 is necessary
summary: Prometheus Ceph Exporter
description: |
  Exporter that exposes information gathered from Ceph for use by the Prometheus monitoring system
confinement: strict
parts:
  ceph-exporter:
    plugin: go
    source: https://github.com/digitalocean/ceph_exporter.git
    go-importpath: github.com/digitalocean/ceph_exporter
    source-branch: nautilus
    build-packages:
      - librados-dev
      - libnss3
      - libsqlite3-0
      - gcc
    prime:
      - bin/ceph_exporter
  ceph-exporter-config:
    plugin: dump
    source: .
    organize:
      daemon_arguments: etc/ceph_exporter/daemon_arguments.example
      ceph_exporter_wrapper: bin/ceph_exporter.wrapper
    stage-packages:
      - librados2
      - libgtk3-nocsd0
      - libnss3
      - libstdc++6
    prime:
      - etc/ceph_exporter/daemon_arguments.example
      - bin/ceph_exporter.wrapper
      - lib/*
      - usr/lib/*
apps:
  ceph-exporter:
    command: 'bin/ceph_exporter.wrapper'
    plugs: [network-bind]
    daemon: simple
