name: prometheus-ceph-exporter
version: 0.3.0
summary: Prometheus Ceph Exporter
description: |
  Exporter that exposes information gathered from Ceph for use by the Prometheus monitoring system
confinement: strict

parts:
  ceph-exporter:
    plugin: go
    source: https://github.com/digitalocean/ceph_exporter.git
    go-importpath: github.com/digitalocean/ceph_exporter
    source-tag: 1.0.0
    build-packages: [librados-dev]
    prime:
      - bin/ceph_exporter
  ceph-exporter-config:
    plugin: dump
    source: .
    organize:
      daemon_arguments: etc/ceph_exporter/daemon_arguments.example
      ceph_exporter_wrapper: bin/ceph_exporter.wrapper
    prime:
      - etc/ceph_exporter/daemon_arguments.example
      - bin/ceph_exporter.wrapper
apps:
  ceph-exporter:
    command: 'bin/ceph_exporter.wrapper'
    plugs: [network-bind]
    daemon: simple
